# Generated by Django 5.2.8 on 2025-12-05 05:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peluqueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('nombre_visible', models.CharField(default='Mi Salón', max_length=100)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hora_apertura', models.TimeField(default='08:00')),
                ('hora_cierre', models.TimeField(default='20:00')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peluqueria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.peluqueria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Duración estimada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peluqueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='salon.peluqueria')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('peluqueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='salon.peluqueria')),
                ('servicios_que_realiza', models.ManyToManyField(to='salon.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmada'), ('A', 'Anulada')], default='P', max_length=1)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.empleado')),
                ('peluqueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.peluqueria')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descanso_inicio', models.TimeField(blank=True, help_text='Inicio hora almuerzo (opcional)', null=True)),
                ('descanso_fin', models.TimeField(blank=True, help_text='Fin hora almuerzo (opcional)', null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='salon.empleado')),
                ('peluqueria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.peluqueria')),
            ],
            options={
                'unique_together': {('empleado', 'dia_semana')},
            },
        ),
    ]
