# Generated by Django 5.2.8 on 2025-12-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosemanal',
            name='descanso_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariosemanal',
            name='descanso_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
