# Generated by Django 5.1.4 on 2025-12-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="ciudad",
            field=models.CharField(default="Tunja", max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="facebook",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="instagram",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="latitud",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="longitud",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tiktok",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="address_delivery",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="is_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
        migrations.AlterField(
            model_name="professional",
            name="balance_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="professional",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="professional",
            name="is_external",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="professional",
            name="payment_info",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="professional",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="subdomain",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Identificador (Slug)"
            ),
        ),
    ]
