# Generated by Django 5.2.8 on 2025-11-30 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_servicio_precio_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='horario_fin',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='horario_inicio',
        ),
        migrations.CreateModel(
            name='HorarioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_semanales', to='salon.empleado')),
            ],
            options={
                'verbose_name': 'Horario Semanal',
                'verbose_name_plural': 'Horarios Semanales',
                'unique_together': {('empleado', 'dia_semana')},
            },
        ),
    ]
