# Generated by Django 5.1.4 on 2025-12-13 23:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0002_tenant_ciudad_tenant_facebook_tenant_instagram_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"verbose_name": "Cita", "verbose_name_plural": "Citas"},
        ),
        migrations.AlterModelOptions(
            name="externalpayment",
            options={
                "verbose_name": "Pago Externo",
                "verbose_name_plural": "Pagos Externos",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Producto", "verbose_name_plural": "Inventario"},
        ),
        migrations.AlterModelOptions(
            name="professional",
            options={
                "verbose_name": "Profesional",
                "verbose_name_plural": "Profesionales",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Servicio", "verbose_name_plural": "Servicios"},
        ),
        migrations.AlterModelOptions(
            name="tenant",
            options={"verbose_name": "Negocio", "verbose_name_plural": "Negocios"},
        ),
        migrations.RenameField(
            model_name="externalpayment",
            old_name="date_paid",
            new_name="fecha",
        ),
        migrations.RenameField(
            model_name="externalpayment",
            old_name="amount",
            new_name="monto",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="address_delivery",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="customer_phone",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="is_delivery",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="professional",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="service",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="time",
        ),
        migrations.RemoveField(
            model_name="externalpayment",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="externalpayment",
            name="professional",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="balance_due",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="commission_rate",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="invite_token",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="is_external",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="name",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="payment_info",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="telegram_chat_id",
        ),
        migrations.RemoveField(
            model_name="service",
            name="duration_min",
        ),
        migrations.RemoveField(
            model_name="service",
            name="name",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="address",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="latitud",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="longitud",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="users",
        ),
        migrations.AddField(
            model_name="appointment",
            name="cliente_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email Cliente"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cliente_nombre",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=100,
                verbose_name="Nombre Cliente",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="cliente_telefono",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=20,
                verbose_name="Teléfono Cliente",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="empleado",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="salon.professional",
                verbose_name="Profesional",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                    ("completada", "Completada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="fecha_hora_inicio",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha y Hora"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="precio_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total a Pagar"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="servicio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="salon.service",
                verbose_name="Servicio",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="externalpayment",
            name="estado",
            field=models.CharField(default="pendiente", max_length=20),
        ),
        migrations.AddField(
            model_name="externalpayment",
            name="referencia",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="externalpayment",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="salon.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="nombre",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Nombre del Producto"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Precio"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professional",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo Electrónico"
            ),
        ),
        migrations.AddField(
            model_name="professional",
            name="especialidad",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Especialidad"
            ),
        ),
        migrations.AddField(
            model_name="professional",
            name="nombre",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Nombre Completo"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professional",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Teléfono"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="descripcion",
            field=models.TextField(blank=True, null=True, verbose_name="Descripción"),
        ),
        migrations.AddField(
            model_name="service",
            name="duracion",
            field=models.IntegerField(
                default=1,
                help_text="Duración en minutos",
                verbose_name="Duración (min)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="nombre",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Nombre del Servicio"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Precio"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenant",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Teléfono"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dueño",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="salon.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0, verbose_name="Cantidad Disponible"),
        ),
        migrations.AlterField(
            model_name="product",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="salon.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professionals",
                to="salon.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professional_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="salon.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="bold_api_key",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="API Key Bold"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="ciudad",
            field=models.CharField(
                default="Tunja", max_length=100, verbose_name="Ciudad"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="facebook",
            field=models.URLField(blank=True, null=True, verbose_name="Facebook"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="instagram",
            field=models.URLField(blank=True, null=True, verbose_name="Instagram"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre del Negocio"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="nequi_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Nequi"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="subdomain",
            field=models.SlugField(unique=True, verbose_name="Identificador (URL)"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tiktok",
            field=models.URLField(blank=True, null=True, verbose_name="TikTok"),
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(verbose_name="Inicio Ausencia")),
                ("fecha_fin", models.DateTimeField(verbose_name="Fin Ausencia")),
                (
                    "motivo",
                    models.CharField(blank=True, max_length=200, verbose_name="Motivo"),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="salon.professional",
                        verbose_name="Profesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ausencia",
                "verbose_name_plural": "Ausencias",
                "ordering": ["fecha_inicio"],
            },
        ),
    ]
