# Generated by Django 5.2.8 on 2025-12-05 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_horariosemanal_descanso_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='servicio',
        ),
        migrations.AddField(
            model_name='cita',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(to='salon.servicio'),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='direccion',
            field=models.CharField(blank=True, help_text='Ej: Calle 123 #45-67', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='telefono',
            field=models.CharField(blank=True, help_text='Ej: +57 300 123 4567', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
