# Generated by Django 5.2.8 on 2025-12-04 20:52

import django.db.models.deletion
import django_multitenant.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_remove_empleado_horario_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peluqueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_visible', models.CharField(default='Mi Salón', max_length=100)),
            ],
        ),
        migrations.AlterModelManagers(
            name='cita',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='empleado',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='horariosemanal',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='servicio',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='horariosemanal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cita',
            name='peluqueria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.peluqueria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='peluqueria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.peluqueria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horariosemanal',
            name='peluqueria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.peluqueria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='peluqueria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.peluqueria'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='horariosemanal',
            unique_together={('peluqueria', 'empleado', 'dia_semana')},
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peluqueria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.peluqueria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
