# Generated by Django 5.2.8 on 2025-12-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_remove_cita_servicio_cita_precio_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluqueria',
            name='telegram_token',
            field=models.CharField(blank=True, help_text='Token del bot creado con @BotFather', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='peluqueria',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID de chat del dueño para recibir avisos', max_length=100, null=True),
        ),
    ]
