# Generated by Django 5.2.8 on 2025-12-04 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_peluqueria_alter_cita_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariosemanal',
            options={},
        ),
        migrations.AlterModelManagers(
            name='cita',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='empleado',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='horariosemanal',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='servicio',
            managers=[
            ],
        ),
        migrations.AlterUniqueTogether(
            name='horariosemanal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmada'), ('A', 'Anulada')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='peluqueria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='salon.peluqueria'),
        ),
        migrations.AlterField(
            model_name='horariosemanal',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='salon.empleado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='peluqueria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='salon.peluqueria'),
        ),
        migrations.AlterUniqueTogether(
            name='horariosemanal',
            unique_together={('empleado', 'dia_semana')},
        ),
    ]
