# Generated by Manual Migration for PASO

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_peluqueria_telegram_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluqueria',
            name='porcentaje_abono',
            field=models.IntegerField(default=50, help_text='Porcentaje que debe pagar el cliente para reservar (Ej: 20, 30, 50).'),
        ),
    ]
