# Generated by Django 5.2.8 on 2025-12-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_alter_horariosemanal_options_alter_cita_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluqueria',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID del chat de Telegram (ej: -123456789) para notificaciones individuales.', max_length=100, null=True),
        ),
    ]
