# Generated by Django 5.1.4 on 2025-12-09 21:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_peluqueria_porcentaje_abono'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('nicho', models.CharField(max_length=50)),
                ('cantidad_empleados', models.CharField(max_length=50)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='servicios_que_realiza',
        ),
        migrations.RemoveField(
            model_name='peluqueria',
            name='hora_apertura',
        ),
        migrations.RemoveField(
            model_name='peluqueria',
            name='hora_cierre',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='cita',
            name='abono_pagado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cita',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='referencia_pago_bold',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='bold_api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='bold_integrity_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='ciudad',
            field=models.CharField(default='Tunja', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='es_dueño',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente_nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente Pago'), ('C', 'Confirmada'), ('A', 'Anulada')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='cita',
            name='peluqueria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='salon.peluqueria'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='precio_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peluqueria',
            name='direccion',
            field=models.CharField(blank=True, default='Sin dirección', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peluqueria',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='peluqueria',
            name='nombre_visible',
            field=models.CharField(default='Mi Salón', max_length=200),
        ),
        migrations.AlterField(
            model_name='peluqueria',
            name='porcentaje_abono',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='peluqueria',
            name='slug',
            field=models.SlugField(default='salon-temp', help_text='Identificador único en la URL (ej: mi-salon)', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peluqueria',
            name='telefono',
            field=models.CharField(blank=True, default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peluqueria',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='peluqueria',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='peluqueria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.peluqueria'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='salon.empleado')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.DeleteModel(
            name='HorarioSemanal',
        ),
    ]
