# Generated by Django 5.1.4 on 2025-12-09 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_solicitudsaas_remove_empleado_servicios_que_realiza_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horarioempleado',
            name='almuerzo_fin',
            field=models.TimeField(blank=True, help_text='Fin del descanso', null=True),
        ),
        migrations.AddField(
            model_name='horarioempleado',
            name='almuerzo_inicio',
            field=models.TimeField(blank=True, help_text='Inicio del descanso', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='horarioempleado',
            unique_together={('empleado', 'dia_semana')},
        ),
    ]
