# Generated by Django 5.2.8 on 2025-12-05 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_peluqueria_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duracion_minutos',
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Duración estimada'),
        ),
        migrations.AlterField(
            model_name='peluqueria',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID del chat de Telegram (ej: -100123456789) para notificaciones.', max_length=100, null=True),
        ),
    ]
