# Generated by Django 5.1.4

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_empleado_email_contacto_empleado_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluqueria',
            name='codigo_pais_wa',
            field=models.CharField(default='57', help_text='Código de país para WhatsApp', max_length=5),
        ),
        migrations.AlterField(
            model_name='horarioempleado',
            name='almuerzo_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horarioempleado',
            name='almuerzo_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
