# Generated by Django 5.2.8 on 2025-12-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_remove_servicio_duracion_minutos_servicio_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peluqueria',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID del chat (ej: 8345213799 para privado, o -100... para grupos).', max_length=100, null=True),
        ),
    ]
