# Generated by Django 5.2.8 on 2025-12-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_alter_peluqueria_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosemanal',
            name='descanso_fin',
            field=models.TimeField(blank=True, help_text='Fin hora almuerzo (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='horariosemanal',
            name='descanso_inicio',
            field=models.TimeField(blank=True, help_text='Inicio hora almuerzo (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='hora_apertura',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='peluqueria',
            name='hora_cierre',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AlterField(
            model_name='horariosemanal',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AlterField(
            model_name='peluqueria',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
