# Generated by Django 5.1.4 on 2025-12-10 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0009_ajustes_finales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("P", "Pendiente Pago"),
                    ("C", "Confirmada"),
                    ("X", "Cancelada"),
                ],
                default="C",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="bold_api_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Bold API Key"
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="bold_integrity_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Bold Integrity Key"
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="codigo_pais_wa",
            field=models.CharField(
                default="57", help_text="Cód. País WhatsApp", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="Identificador único en la URL", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="peluqueria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="salon.peluqueria",
            ),
        ),
    ]
