# Generated by Django 5.2.8 on 2025-12-05 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_horariosemanal_descanso_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosemanal',
            name='peluqueria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon.peluqueria'),
        ),
    ]
