# Generated by Django 5.1.4 on 2025-12-11 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0010_alter_cita_estado_alter_peluqueria_bold_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="descuento_aplicado",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="peluqueria",
            name="latitud",
            field=models.FloatField(default=5.5353),
        ),
        migrations.AddField(
            model_name="peluqueria",
            name="longitud",
            field=models.FloatField(default=-73.3678),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="hora_apertura",
            field=models.TimeField(default="08:00", help_text="Hora de apertura"),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="hora_cierre",
            field=models.TimeField(default="20:00", help_text="Hora de cierre"),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="porcentaje_abono",
            field=models.IntegerField(default=50, help_text="Porcentaje para reservar"),
        ),
        migrations.CreateModel(
            name="Cupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("porcentaje_descuento", models.IntegerField(default=10)),
                ("activo", models.BooleanField(default=True)),
                ("usos_restantes", models.IntegerField(default=100)),
                (
                    "peluqueria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cupones",
                        to="salon.peluqueria",
                    ),
                ),
            ],
        ),
    ]
