# Generated by Django 5.1.4 on 2025-12-11 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0011_cita_descuento_aplicado_peluqueria_latitud_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionPlataforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solo_un_registro",
                    models.CharField(
                        default="X",
                        editable=False,
                        help_text="Configuración única del sistema",
                        max_length=1,
                    ),
                ),
                (
                    "bold_api_key",
                    models.CharField(
                        default="g4XAZfPD4hH2e5WXhiKfZjGPLRxrzbPH9rOxaqJhDTw",
                        max_length=255,
                        verbose_name="Tu API Key (Identity)",
                    ),
                ),
                (
                    "bold_secret_key",
                    models.CharField(
                        default="te4T6sOL43wDlcGwCGHfGA",
                        max_length=255,
                        verbose_name="Tu Secret Key",
                    ),
                ),
                (
                    "bold_integrity_key",
                    models.CharField(
                        default="CAMBIAR_EN_ADMIN",
                        help_text="Busca la 'Llave de Integridad' en tu panel de Bold y pégala aquí",
                        max_length=255,
                        verbose_name="Tu Integrity Key",
                    ),
                ),
                (
                    "telegram_token",
                    models.CharField(
                        blank=True,
                        help_text="Token de tu Bot de Telegram",
                        max_length=255,
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True,
                        help_text="Tu ID de Chat para recibir alertas",
                        max_length=255,
                    ),
                ),
                (
                    "precio_mensualidad",
                    models.IntegerField(
                        default=130000, help_text="Valor a cobrar mensualmente"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración Dueño PASO",
                "verbose_name_plural": "Configuración Dueño PASO",
            },
        ),
        migrations.AddField(
            model_name="peluqueria",
            name="activo_saas",
            field=models.BooleanField(
                default=True, help_text="Desmarcar si no paga la mensualidad"
            ),
        ),
        migrations.AddField(
            model_name="peluqueria",
            name="fecha_inicio_contrato",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Fecha de registro/inicio suscripción",
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="bold_api_key",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Bold API Key (Cliente)",
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="bold_integrity_key",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Bold Integrity Key (Cliente)",
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="bold_secret_key",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Bold Secret Key (Cliente)",
            ),
        ),
    ]
