# Generated by Django 5.1.4 on 2025-12-11 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0012_configuracionplataforma_peluqueria_activo_saas_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="horarioempleado",
            options={},
        ),
        migrations.RemoveField(
            model_name="configuracionplataforma",
            name="bold_integrity_key",
        ),
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[("P", "Pendiente"), ("C", "Confirmada"), ("X", "Cancelada")],
                default="C",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="configuracionplataforma",
            name="bold_api_key",
            field=models.CharField(
                default="g4XAZfPD4hH2e5WXhiKfZjGPLRxrzbPH9rOxaqJhDTw",
                help_text="La llave pública",
                max_length=255,
                verbose_name="Bold Identidad (API Key)",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionplataforma",
            name="bold_secret_key",
            field=models.CharField(
                default="te4T6sOL43wDlcGwCGHfGA",
                help_text="La llave oculta (empieza con sk_...)",
                max_length=255,
                verbose_name="Bold Llave Secreta",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionplataforma",
            name="precio_mensualidad",
            field=models.IntegerField(default=130000),
        ),
        migrations.AlterField(
            model_name="configuracionplataforma",
            name="solo_un_registro",
            field=models.CharField(default="X", editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name="configuracionplataforma",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="configuracionplataforma",
            name="telegram_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="horarioempleado",
            name="dia_semana",
            field=models.IntegerField(
                choices=[
                    (0, "L"),
                    (1, "M"),
                    (2, "X"),
                    (3, "J"),
                    (4, "V"),
                    (5, "S"),
                    (6, "D"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="activo_saas",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="bold_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="bold_integrity_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="bold_secret_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="codigo_pais_wa",
            field=models.CharField(default="57", max_length=5),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="fecha_inicio_contrato",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="hora_apertura",
            field=models.TimeField(default="08:00"),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="hora_cierre",
            field=models.TimeField(default="20:00"),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="porcentaje_abono",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
