# Generated by Django 5.1.4 on 2025-12-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0013_alter_horarioempleado_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracionplataforma",
            name="bold_api_key",
        ),
        migrations.RemoveField(
            model_name="configuracionplataforma",
            name="bold_secret_key",
        ),
        migrations.AddField(
            model_name="configuracionplataforma",
            name="link_pago_bold",
            field=models.URLField(
                default="https://checkout.bold.co/payment/LNK_QZ5NWWY82P",
                help_text="Pega aquí el Link de Pago Único de Bold.",
                verbose_name="Link de Pago Bold",
            ),
        ),
    ]
