# Generated by Django 5.1.4 on 2025-12-12 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0014_remove_configuracionplataforma_bold_api_key_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cita",
            old_name="referencia_pago_bold",
            new_name="referencia_pago",
        ),
        migrations.AddField(
            model_name="ausencia",
            name="creado_en",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cita",
            name="metodo_pago",
            field=models.CharField(
                choices=[("BOLD", "Bold"), ("NEQUI", "Nequi"), ("SITIO", "En Sitio")],
                default="SITIO",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="configuracionplataforma",
            name="bold_secret_key",
            field=models.CharField(
                blank=True,
                help_text="Tu llave secreta de Bold para generar cobros",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="peluqueria",
            name="nequi_celular",
            field=models.CharField(
                blank=True,
                help_text="Número Nequi para transferencias",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="peluqueria",
            name="nequi_qr_imagen",
            field=models.ImageField(
                blank=True,
                help_text="Sube el QR de Nequi",
                null=True,
                upload_to="qrs_nequi/",
            ),
        ),
        migrations.AlterField(
            model_name="ausencia",
            name="empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ausencias",
                to="salon.empleado",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionplataforma",
            name="link_pago_bold",
            field=models.URLField(
                default="https://checkout.bold.co/payment/LNK_QZ5NWWY82P",
                verbose_name="Link de Pago Bold (Respaldo)",
            ),
        ),
    ]
