# Generated by Django 5.1.4 on 2025-12-12 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0015_rename_referencia_pago_bold_cita_referencia_pago_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracionplataforma",
            options={"verbose_name_plural": "Configuración Dueño PASO"},
        ),
        migrations.RemoveField(
            model_name="cita",
            name="descuento_aplicado",
        ),
        migrations.RemoveField(
            model_name="peluqueria",
            name="bold_integrity_key",
        ),
        migrations.AlterField(
            model_name="ausencia",
            name="creado_en",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="configuracionplataforma",
            name="bold_secret_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="configuracionplataforma",
            name="link_pago_bold",
            field=models.URLField(
                default="https://checkout.bold.co/payment/LNK_QZ5NWWY82P",
                verbose_name="Link Respaldo",
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="bold_api_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Llave de Identidad"
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="bold_secret_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Llave Secreta"
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="nequi_celular",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="nequi_qr_imagen",
            field=models.ImageField(blank=True, null=True, upload_to="qrs_nequi/"),
        ),
    ]
