# Generated by Django 5.1.4 on 2025-12-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0016_alter_configuracionplataforma_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="tipo_cobro",
            field=models.CharField(
                choices=[("TOTAL", "Pago Completo"), ("ABONO", "Solo Abono")],
                default="TOTAL",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="bold_api_key",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Llave de Identidad (Bold)",
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="bold_secret_key",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Llave Secreta (Bold)",
            ),
        ),
        migrations.AlterField(
            model_name="peluqueria",
            name="porcentaje_abono",
            field=models.IntegerField(
                default=50, help_text="Porcentaje mínimo para reservar (ej: 50)"
            ),
        ),
    ]
