# Generated by Django 5.1.4 on 2025-12-13 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0017_cita_tipo_cobro_alter_peluqueria_bold_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="direccion_domicilio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cita",
            name="es_domicilio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empleado",
            name="es_domiciliario",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empleado",
            name="instagram",
            field=models.CharField(
                blank=True, help_text="Usuario de IG (sin @)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tipo_pago",
            field=models.CharField(
                choices=[("PORCENTAJE", "Porcentaje"), ("FIJO", "Sueldo Fijo")],
                default="PORCENTAJE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="valor_pago",
            field=models.IntegerField(
                default=50, help_text="Si es porcentaje: ej 50. Si es fijo: ej 1200000"
            ),
        ),
        migrations.AddField(
            model_name="peluqueria",
            name="comision_domicilio",
            field=models.IntegerField(
                default=10,
                help_text="Porcentaje de comisión para el dueño por servicio a domicilio",
            ),
        ),
        migrations.AddField(
            model_name="peluqueria",
            name="facebook",
            field=models.URLField(
                blank=True, help_text="Link completo de Facebook", null=True
            ),
        ),
        migrations.AddField(
            model_name="peluqueria",
            name="instagram",
            field=models.URLField(
                blank=True, help_text="Link completo de Instagram", null=True
            ),
        ),
        migrations.AddField(
            model_name="peluqueria",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Sube tu logo (preferiblemente fondo transparente)",
                null=True,
                upload_to="logos_peluqueria/",
            ),
        ),
        migrations.AddField(
            model_name="peluqueria",
            name="ofrece_domicilio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="peluqueria",
            name="tiktok",
            field=models.URLField(
                blank=True, help_text="Link completo de TikTok", null=True
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="cantidad_descuento",
            field=models.IntegerField(
                default=1, help_text="Cantidad a descontar del inventario"
            ),
        ),
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("P", "Pendiente"),
                    ("C", "Confirmada"),
                    ("X", "Cancelada"),
                    ("F", "Finalizada"),
                ],
                default="C",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "costo_compra",
                    models.IntegerField(
                        default=0, help_text="Cuánto te costó comprarlo"
                    ),
                ),
                (
                    "precio_venta",
                    models.IntegerField(
                        default=0, help_text="A cómo lo vendes al público"
                    ),
                ),
                ("cantidad_actual", models.IntegerField(default=0)),
                (
                    "stock_minimo",
                    models.IntegerField(
                        default=5, help_text="Alerta cuando baje de este número"
                    ),
                ),
                (
                    "es_insumo_interno",
                    models.BooleanField(
                        default=False,
                        help_text="Marcar si es un producto de uso interno (shampoo de lavacabezas) y no para venta",
                    ),
                ),
                (
                    "peluqueria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario",
                        to="salon.peluqueria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Compra/Entrada"),
                            ("SALIDA", "Venta/Uso"),
                            ("AJUSTE", "Ajuste Manual"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="salon.producto"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="servicio",
            name="producto_asociado",
            field=models.ForeignKey(
                blank=True,
                help_text="Producto que se descuenta al realizar este servicio (opcional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="salon.producto",
            ),
        ),
    ]
