# Generated by Django 5.1.4 on 2025-12-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0018_cita_direccion_domicilio_cita_es_domicilio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="bold_api_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Mi API Key Bold"
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="bold_secret_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Mi Secret Key Bold"
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="es_independiente",
            field=models.BooleanField(
                default=False,
                help_text="Si está marcado, usa sus propias credenciales de pago y Telegram.",
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Mi Chat ID"
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="telegram_token",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Mi Token Bot"
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="valor_pago",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="producto",
            name="costo_compra",
            field=models.IntegerField(
                default=0, help_text="Costo unitario de adquisición"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="es_insumo_interno",
            field=models.BooleanField(
                default=False, help_text="Marcar si es uso interno (no venta)"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_venta",
            field=models.IntegerField(
                default=0, help_text="Precio de venta al público"
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="cantidad_descuento",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="producto_asociado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="salon.producto",
            ),
        ),
    ]
