# Generated by Django 5.1.4 on 2025-12-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0021_reconciliar_cambios"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="es_domiciliario",
            field=models.BooleanField(default=False),
        ),
    ]
