# Generated by Django 5.1.4 on 2025-12-13 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0022_alter_empleado_es_domiciliario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_phone", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("CONFIRMED", "Confirmada"),
                            ("COMPLETED", "Completada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "is_delivery",
                    models.BooleanField(default=False, verbose_name="Es Domicilio"),
                ),
                (
                    "address_delivery",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dirección Domicilio"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paid", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profesionales/"
                    ),
                ),
                (
                    "is_external",
                    models.BooleanField(
                        default=False, verbose_name="Es Domiciliario Externo"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="% Comisión Dueño",
                    ),
                ),
                (
                    "payment_info",
                    models.TextField(blank=True, verbose_name="Datos Bancarios"),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ID Telegram"
                    ),
                ),
                ("invite_token", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Saldo a Pagar",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration_min", models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nombre del Salón"),
                ),
                ("subdomain", models.CharField(max_length=100, unique=True)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "nequi_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Nequi del Negocio"
                    ),
                ),
                (
                    "bold_api_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Api Key Bold"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="tenants", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="ausencia",
            name="empleado",
        ),
        migrations.RemoveField(
            model_name="cita",
            name="empleado",
        ),
        migrations.RemoveField(
            model_name="cita",
            name="peluqueria",
        ),
        migrations.RemoveField(
            model_name="cita",
            name="servicios",
        ),
        migrations.DeleteModel(
            name="ConfiguracionPlataforma",
        ),
        migrations.RemoveField(
            model_name="cupon",
            name="peluqueria",
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="peluqueria",
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="user",
        ),
        migrations.RemoveField(
            model_name="horarioempleado",
            name="empleado",
        ),
        migrations.AlterUniqueTogether(
            name="horarioempleado",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="movimientoinventario",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="peluqueria",
        ),
        migrations.RemoveField(
            model_name="perfilusuario",
            name="peluqueria",
        ),
        migrations.RemoveField(
            model_name="servicio",
            name="peluqueria",
        ),
        migrations.RemoveField(
            model_name="perfilusuario",
            name="user",
        ),
        migrations.RemoveField(
            model_name="servicio",
            name="producto_asociado",
        ),
        migrations.DeleteModel(
            name="SolicitudSaaS",
        ),
        migrations.AddField(
            model_name="externalpayment",
            name="professional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="salon.professional"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="professional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="salon.professional"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="salon.service"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="salon.tenant"
            ),
        ),
        migrations.AddField(
            model_name="professional",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="salon.tenant"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="salon.tenant"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="salon.tenant"
            ),
        ),
        migrations.DeleteModel(
            name="Ausencia",
        ),
        migrations.DeleteModel(
            name="Cita",
        ),
        migrations.DeleteModel(
            name="Cupon",
        ),
        migrations.DeleteModel(
            name="Empleado",
        ),
        migrations.DeleteModel(
            name="HorarioEmpleado",
        ),
        migrations.DeleteModel(
            name="MovimientoInventario",
        ),
        migrations.DeleteModel(
            name="Peluqueria",
        ),
        migrations.DeleteModel(
            name="PerfilUsuario",
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
        migrations.DeleteModel(
            name="Servicio",
        ),
    ]
